## Aggregations
#### Summing the values in an array

In [1]:
import numpy as np

In [3]:
x = np.random.random(100)
print(x)
sum(x)

[0.20457814 0.2409316  0.32777339 0.80502488 0.43899637 0.77074885
 0.17817542 0.60982867 0.13756508 0.36398757 0.88152516 0.03462748
 0.81882877 0.21736601 0.62076396 0.21851575 0.76192654 0.7269296
 0.28847769 0.97496449 0.76869668 0.45600995 0.75195778 0.53789664
 0.55869957 0.82916641 0.49369973 0.07546963 0.26407162 0.39192055
 0.76177718 0.4677922  0.2813042  0.7009959  0.98307227 0.79320161
 0.69238148 0.21260103 0.46302605 0.10811922 0.51373288 0.64557009
 0.12432628 0.15687667 0.71466067 0.99883259 0.51052906 0.21491699
 0.94371333 0.83611315 0.2009508  0.46514727 0.03199699 0.32793039
 0.24973855 0.43284066 0.60588569 0.6434285  0.93231712 0.02956054
 0.09986746 0.32752783 0.9642708  0.00626964 0.84469355 0.95156935
 0.67671921 0.64027986 0.74650691 0.13430528 0.81802718 0.07840156
 0.04478519 0.26795112 0.57443605 0.57023547 0.85723281 0.16055292
 0.43013514 0.59575474 0.10038744 0.62100302 0.33851943 0.47713852
 0.77010438 0.45106193 0.98987031 0.90699062 0.14397326 0.68651

50.45472023539774

In [4]:
big_array = np.random.rand(1000000)
big_array

array([4.91146611e-04, 2.18186823e-01, 1.11331764e-01, ...,
       5.05800271e-01, 5.72385515e-01, 9.27003565e-01])

In [8]:
%timeit  sum(big_array)
%timeit np.sum(big_array)

89.9 ms ± 3.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
411 μs ± 5.53 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
min(big_array),max(big_array)

(3.192187899903054e-06, 0.9999982595400169)

In [15]:
np.min(big_array),np.max(big_array),np.sum(big_array)
# ==
big_array.min(),big_array.max(),big_array.sum()

(3.192187899903054e-06, 0.9999982595400169, 499574.64773806685)

In [11]:
%timeit  min(big_array)
%timeit np.min(big_array)

59.1 ms ± 2.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
331 μs ± 18.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Multi dimensional aggregates

In [17]:
x = np.arange(0,6).reshape((2,3)) 
x

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
x.sum() # == 
np.sum(x) #!= sum(x)

15

In [35]:
x.sum(axis=0,keepdims=True)

array([[3, 5, 7]])

In [36]:
x.sum(axis=1,keepdims=True)

array([[ 3],
       [12]])

|Function Name| NaN-safe Version| Description|
| :- | -: | :-: |
|np.sum |np.nansum|Compute sum of elements|
|p.prod	|np.nanprod|Compute product of elements|
|np.mean|np.nanmean|Compute median of elements|
|np.std	|np.nanstd|	Compute standard deviation|
|np.var	|np.nanvar|Compute variance|
|np.min	|np.nanmin|Find minimum value|
|np.max	|np.nanmax|Find maximum value|
|np.argmin|	пр.nanargmin|Find index of minimum value|
|np.argmax	|np.nanargmax|Find index of maximum value|
|np.median|	np.nanmedian|Compute median of elements|
|np.percentile |p.nanpercentile|Compute rank-based statistics of elements|
|np.any	|N/A|Evaluate whether any elements are true|
|np.all|N/A	|Evaluate whether all elements are true|
