In [1]:
import numpy as np

In [21]:
x = np.zeros((3,4,5), dtype = "int")

In [19]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x)
print(x.dtype)


3
(3, 4, 5)
60
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
int16


In [22]:
x = np.ones((3,4,5), dtype = "int")

In [23]:
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [24]:
x = np.array([1,2,3,4,6,-2,-2,-5,6])

In [25]:
x[0]

1

In [26]:
x[-1]

6

In [27]:
x[-2]

-5

## Slicing in multi-dimensional array 

In [28]:
x = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [29]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
x[0,0]

0

In [31]:
[1,1]

[1, 1]

In [38]:
x[0,0] = 5

In [39]:
x

array([[ 5,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
x[:2]

array([[5, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
x[2::]

array([[ 8,  9, 10, 11]])

In [53]:
x[0::]

array([[ 5,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
x[0:2,2:3]

array([[2],
       [6]])

In [62]:
x[0,2:4]

array([2, 3])

In [68]:
x[:3,::2]

array([[ 5,  2],
       [ 4,  6],
       [ 8, 10]])

In [73]:
x[::2,::2]

array([[ 5,  2],
       [ 8, 10]])

In [74]:
x[::2,2::]

array([[ 2,  3],
       [10, 11]])

In [75]:
x[2::,2::]

array([[10, 11]])

In [76]:
x[::-1,::-1] #reverse

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  5]])

In [77]:
x[:2,::-1]

array([[3, 2, 1, 5],
       [7, 6, 5, 4]])

In [84]:
x[0] = [0,1,2,3]


In [85]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
x[::-1,:2]


array([[8, 9],
       [4, 5],
       [0, 1]])

In [95]:
x[:2,::-1]


array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

In [96]:
x[:,0]

array([0, 4, 8])

In [97]:
x[0,:]

array([0, 1, 2, 3])

## Array attributes and indexing


In [99]:
np.random.random((3,3)) #Uniformally distributed means between 0,1

array([[0.74344941, 0.25162201, 0.39861274],
       [0.95136709, 0.86104479, 0.31643815],
       [0.13205677, 0.58390581, 0.19612694]])

In [100]:
np.random.normal(0,1,(3,3)) #with 0 mean, and 1 standard deviation

array([[ 2.19217139,  2.10217031,  0.87034371],
       [-1.69207283, -0.70427563,  0.19975752],
       [-0.34634138,  0.24650633,  1.41823598]])

In [101]:
np.random.randint(1,10,(3,3)) #interval in 1-10

array([[4, 4, 4],
       [8, 5, 6],
       [3, 5, 2]])

In [103]:
np.eye(5,dtype = 'int') #identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [107]:
np.empty((3,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Slicing in 1D Arrays: Accessing subarrays



In [109]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
x[1:5]

array([1, 2, 3, 4])

In [111]:
x[:3]

array([0, 1, 2])

In [112]:
x[::2]

array([0, 2, 4, 6, 8])

In [113]:
x[2::]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [116]:
x[1::2]

array([1, 3, 5, 7, 9])

In [117]:
x[3::3]

array([3, 6, 9])

In [118]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [119]:
x[::-2]

array([9, 7, 5, 3, 1])

In [120]:
x[5::-2]

array([5, 3, 1])

## Coping arrays

In [57]:
import numpy as np
x = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
sub_x = x.copy()

In [55]:
sub_x[0,0] = 1 
sub_x



array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##  Reshape Arrays

In [54]:
import numpy as np


In [81]:
x = np.arange(1,10).reshape((3,3))
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
x.shape

(3, 3)

In [90]:
x = np.array([1,2,3])
# row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [93]:
x.reshape((1,3)).shape

(1, 3)

In [92]:
x.reshape(3,1) #column vector via reshape

array([[1],
       [2],
       [3]])

In [99]:
x[np.newaxis,:].shape # row vector via newaxis (alternative way)

(1, 3)

In [102]:
x[:,np.newaxis].shape # column vector via newaxis (alternative way)

(3, 1)

In [101]:
x.shape

(3,)

In [124]:
grid = np.arange(16)
grid


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [145]:
grid.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [134]:
grid.reshape((4,-1,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

## Array concatenation

In [159]:
x = np.arange(3)
y = np.arange(3,6)
k = np.concatenate((x,y))

In [160]:
z = np.arange(6,9)
np.concatenate([x,y,z])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
# for 2D matrix 
x = np.full((3,3),1)
y = np.full((3,3),2)
print(x)
print()
print(y)


[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [166]:
# contatenate along the first axis (rows)
np.concatenate([x,y],axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [169]:
# contatenate along the second axis (colums)
np.concatenate([x,y],axis=1) 

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [228]:
x = np.arange(1,4)
x
grid = np.arange(0,12).reshape((4,-1))
grid

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [233]:
x = x.reshape((-1,3))
x

array([[1, 2, 3]])

In [234]:
grid

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [235]:
np.concatenate([x,grid],axis=0)

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [236]:
np.vstack((x,grid))

array([[ 1,  2,  3],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [245]:
x = np.arange(1,5).reshape((-1,1))
x

array([[1],
       [2],
       [3],
       [4]])

In [244]:
np.hstack((x,grid))

array([[ 1,  0,  1,  2],
       [ 2,  3,  4,  5],
       [ 3,  6,  7,  8],
       [ 4,  9, 10, 11]])

In [248]:
np.concatenate([x,grid],axis=1)

array([[ 1,  0,  1,  2],
       [ 2,  3,  4,  5],
       [ 3,  6,  7,  8],
       [ 4,  9, 10, 11]])

## Split Arrays

In [285]:
x=np.arange(16)

In [297]:
x1,x2,x3,x4 = np.split(x,[2,5,7])
print(x1,x2,x3,x4)

[0 1] [2 3 4] [5 6] [ 7  8  9 10 11 12 13 14 15]


In [284]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [260]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print()
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [298]:
upper, lower,last = np.vsplit(grid,[1,2])
print(upper)
print()
print(lower)
print()
print(last)

[[0 1 2 3]]

[[4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [261]:
left, right = np.hsplit(grid,[2])
print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
