## Ufuncs
- <b>numpy</b> provides an easy and flexible interface to optimized computation with arrays of data
- <b>Vectorization</b>  is the key for NumPy arrays to be fast
- <b>Vectorization</b> is implemented through a universal function (ufunc)
## Slowness of loops in Python
- Python is dynamic and interpreted
- Various attempts to address this weakness like
  - Pypy project
  - Cython project
  - Numba project
- The main problem with Python is that many small operations are repeated like the following code for computing reciprocals:

In [ ]:
import numpy as np 
np.random.seed(0)

def compute_reciprocals(values):
    lens = len(values)
    output = np.empty(lens)
    for i in range(lens):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1,10,size = 5)
compute_reciprocals(values)


In [6]:
values

array([6, 1, 4, 4, 8])

In [8]:
values = np.random.randint(1,10,size = 1000000)
%timeit compute_reciprocals(values)


1.55 s ± 47.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### NumPy provides a convenient interface for performing similar operations : <b>Vectorization</b>

In [12]:
values = np.random.randint(1,10,size = 5)
values

array([8, 5, 8, 4, 7])

In [13]:
1/values

array([0.125     , 0.2       , 0.125     , 0.25      , 0.14285714])

In [16]:
values = np.random.randint(1,10,size = 1000000)
%timeit 1/values

2.25 ms ± 42.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Exploring NumPy's UFuncs

_unary unfuncs vs binary ufuncs_

#### Array arithmetic

In [17]:
import numpy as np 

In [33]:
x = np.arange(4)
print(x)
print(x+5) # np.add(x,5)
print(x-5) 
print(x*2) # np.multiply(x,2)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]


In [35]:
print(x/2)
print(x//2) # floor division تاخد العدد الصحيح وتترك ما بعد الفاصله
print(-x)
print(x**2) 
print(x%2) # باقي القسمه 


[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]


In [42]:
-(x/2 + 2) 

array([-2. , -2.5, -3. , -3.5])

In [44]:
-(x/2 + 2) **2

array([ -4.  ,  -6.25,  -9.  , -12.25])

In [46]:
x

array([0, 1, 2, 3])

In [48]:
- x/2 + 2 ** 2 ==  - x/2 + (2 ** 2)

array([4. , 3.5, 3. , 2.5])

### Absolute value

In [49]:
x = np.array([-1,2,-2,-8,-3,3])
abs(x)

array([1, 2, 2, 8, 3, 3])

In [52]:
big_array = np.random.randint(-10,10,size = 1000000)
%timeit np.abs(big_array)
%timeit abs(big_array)


1.36 ms ± 61.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
1.35 ms ± 42.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Trigonometric functions الدوال المثلثيه

In [84]:
theta = np.linspace(0,np.pi,3) #Return evenly spaced numbers over a specified interval
np.degrees(theta)
theta

array([0.        , 1.57079633, 3.14159265])

In [83]:
print(theta) # القياس الدائريه
print(np.sin(theta)) #مقابل / الوتر
print(np.cos(theta)) # مجاور / الوتر
print(np.tan(theta)) # المقابل / المجاور

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [70]:
x = [.5,.5,1] # القياس الدائريه
print(x) # قيم الزوايا
print(np.arcsin(x)) # عكس ال  sin 
print(np.arccos(x)) # الجيب التمام
print(np.arctan(x)) # الظل

[0.5, 0.5, 1]
[0.52359878 0.52359878 1.57079633]
[1.04719755 1.04719755 0.        ]
[0.46364761 0.46364761 0.78539816]


In [85]:
x = [1,2,3]
print(x)
print(np.exp(x))
print(np.exp2(x)) # 2 ** x
print(np.power(3,x))# 3 ** x

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [86]:
x = [1,2,4,10]
print(x)
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[1, 2, 4, 10]
[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


## Specialized unfuncs

In [97]:
from scipy import special
#Gamma functions (generalized factorials) and related functions
x = [11, 5, 10]
print("gamma (x) =", special.gamma(x))
print ("In|gamma(x) | =", special.gammaln(x))
print ("beta(x, 2)=", special.beta(x, 2))

gamma (x) = [3.6288e+06 2.4000e+01 3.6288e+05]
In|gamma(x) | = [15.10441257  3.17805383 12.80182748]
beta(x, 2)= [0.00757576 0.03333333 0.00909091]


In [99]:
# Error funition (integral of Gaussian)
# its complement, and its inverse
x = np. array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special. erfc (x))
print ("erfinv(x)=", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)= [0.         0.27246271 0.73286908        inf]


## Advanced Ufunc Features

#### Specifying the output for better memory performance


In [108]:
x = np.arange(5)
y = np.empty(5,dtype = 'int')
print(y)
np.multiply(x, 10, out=y)
print(y)
np.add (y, 10, out=y)
print(y)

[0 1 2 3 4]
[ 0 10 20 30 40]
[10 20 30 40 50]


In [106]:
y = np. zeros (10)
np. power (2, x, out=y[::2])# 2***
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
