## Fancy Indexing

In [21]:
import numpy as np
rand = np. random.RandomState (42)
x = rand. randint (100, size=10)
print (x)

[51 92 14 71 60 20 82 86 74 74]


In [6]:
[x[3], x[7], x[2]]

[71, 86, 14]

In [8]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [9]:
x[[3, 7, 4]]

array([71, 86, 60])

In [13]:
ind = np.array([[3, 7], [4, 5]])
ind
x[ind]

array([[71, 86],
       [60, 20]])

In [12]:
x[np.array([[3, 7], [4, 5]])]

array([[71, 86],
       [60, 20]])

In [29]:
x = np.arange(12).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
x[row, col]

array([ 2,  5, 11])

## Combined Indexing

In [22]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [32]:
x[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
x[[1,2,0]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [36]:
print(x)
x[2,[2,0,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([10,  8,  9])

In [38]:
x[[1,0], 1:]

array([[5, 6, 7],
       [1, 2, 3]])