In [1]:
import numpy as np 


In [100]:
x = np.array([[1,0,3,2],[5,4,6,7]])
x

array([[1, 0, 3, 2],
       [5, 4, 6, 7]])

In [10]:
np.sort(x,axis = 0)

array([[ 1, -4,  3,  2],
       [ 5,  0,  6,  7]])

In [11]:
np.sort(x,axis = 1)

array([[ 0,  1,  2,  3],
       [-4,  5,  6,  7]])

In [53]:
np.sort(x)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [57]:
res = np.sort(x)[:,::-1] # reverse creates new array
res

array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

In [56]:
x[::-1,::-1].sort() # at the same array
x

array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

In [60]:
x.sort()
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
x.argsort()

array([[1, 0, 3, 2],
       [1, 0, 2, 3]])

In [108]:
x = np.array([3,4,5,6,4,8])
indecies = np.argsort(x)
indecies

array([0, 1, 4, 2, 3, 5])

In [112]:
x.sort()
x

array([3, 4, 4, 5, 6, 8])

In [109]:
x[indecies]

array([3, 4, 4, 5, 6, 8])